version: '3'
services:
  app:
    build: ./app
    command: yarn dev
    ports:
     - "3000:3000"
    volumes:
     - ./app:/app
     - /app/node_modules
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    build: ./api
    command: python3 manage.py runserver 0.0.0.0:7000
    ports:
      - "7000:7000"
    volumes:
      - ./api:/api
    depends_on:
      - db
volumes:
  postgres_data: